# Generated by Django 4.2.3 on 2023-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccount',
            name='category',
            field=models.CharField(choices=[('Heart', 'Heart Patients'), ('Liver', 'Liver Patients')], max_length=50),
        ),
    ]
